steps:
#step 1
- name: gcr.io/cloud-builders/docker
  args: [
   'build',
   '-t', 
   'gcr.io/image-347504/imageaudio:$TAG_NAME',
   '-t', 
   'gcr.io/image-347504/imageaudio:latest',
   '.'
  ]

# step 2
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/deployment.yaml']

  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=image'
 
#step 3
- name: 'gcr.io/cloud-builders/kubectl'
  args: [
   'set', 
   'image', 
   'deployment', 
   'imageaudio',
   'imageaudio=gcr.io/image-347504/imageaudio:$TAG_NAME'
  ]
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=image'

images: [
   'gcr.io/image-347504/imageaudio:$TAG_NAME',
   'gcr.io/image-347504/imageaudio:latest'
  ]
