---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: imageaudio
  name: imageaudio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imageaudio
  template:
    metadata:
      labels:
        app: imageaudio
    spec:
      containers:
      - image: gcr.io/image-347015/imageaudio:latest
        name: imageaudio
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: imageaudio
spec:
  selector:
     app: imageaudio
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer


