---
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: imageaudio
  name: imageaudio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imageaudio
  template:
    metadata:
      labels:
        app: imageaudio
    spec:
      containers:
      - image: gcr.io/image-347015/imageaudio:latest
        name: imageaudio
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: imageaudio
spec:
  selector:
     run: imageaudio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: rss-site
#   labels:
#     app: web
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: web
#   template:
#     metadata:
#       labels:
#         app: web
#     spec:
#       containers:
#         - name: front-end
#           image: nginx
#           ports:
#             - containerPort: 80
#         - name: rss-reader
#           image: nickchase/rss-php-nginx:v1
#           ports:
#             - containerPort: 88
